# Generated by Django 4.2.5 on 2023-10-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_alter_groups_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="subjects",
            field=models.ManyToManyField(to="school.subject"),
        ),
    ]
