# Generated by Django 4.2.5 on 2023-10-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_teachers_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachers",
            name="subjects",
            field=models.ManyToManyField(related_name="teachers", to="school.subject"),
        ),
    ]
